language: ruby
sudo: false
branches:
  only:
    - master
rvm:
  - 2.1.9
  - 2.2.4
  - 2.3.1
gemfile:
  - gemfiles/ar_4.1.0.gemfile
  - gemfiles/ar_4.1.7.gemfile
  - gemfiles/ar_4.1.8.gemfile
  - gemfiles/ar_4.2.gemfile
  - gemfiles/ar_5.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    # Rails 5 or later requires Ruby 2.2.0 or newer.
    - rvm: 2.1.9
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/ar_5.gemfile
