language: ruby
sudo: false
branches:
  only:
    - master
rvm:
  - 2.0
  - 2.1
  - 2.2
gemfile:
  - gemfiles/ar_4.1.0.gemfile
  - gemfiles/ar_4.1.7.gemfile
  - gemfiles/ar_4.1.8.gemfile
  - gemfiles/ar_4.2.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    # Rails 5 requires to run on Ruby 2.2.0 or newer.
    - rvm: 2.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile
